//! Every command, and the documented shortcuts. `secondary` is Cmd on macOS
//! and Ctrl elsewhere; Control+Tab cycling is always Control.

use gpui::{actions, App, KeyBinding};

actions!(
  asylum,
  [
    Quit,
    About,
    OpenSettings,
    Palette,
    SearchBots,
    NewChat,
    FindInChat,
    ToggleSidebar,
    FocusPrompt,
    Bot1,
    Bot2,
    Bot3,
    Bot4,
    Bot5,
    Bot6,
    Bot7,
    Bot8,
    Bot9,
    PrevBot,
    NextBot,
    Back,
    Forward,
    CycleNext,
    CyclePrev,
    Marketplace,
    ToggleBotSettings,
    Details,
    SendAnywhere,
    Dictate,
    ZoomIn,
    ZoomOut,
    ZoomReset,
    Fullscreen,
    Cancel,
    CloseWindow,
    OpenComputer,
    OpenBrowser,
    OpenTerminal,
    StopBot,
  ]
);

pub const CONTEXT: &str = "Asylum";

pub fn bind(cx: &mut App) {
  cx.bind_keys([
    KeyBinding::new("secondary-q", Quit, None),
    KeyBinding::new("secondary-,", OpenSettings, None),
    KeyBinding::new("secondary-k", Palette, None),
    KeyBinding::new("secondary-shift-f", SearchBots, None),
    KeyBinding::new("secondary-n", NewChat, None),
    KeyBinding::new("secondary-f", FindInChat, None),
    KeyBinding::new("secondary-b", ToggleSidebar, None),
    KeyBinding::new("secondary-i", FocusPrompt, None),
    KeyBinding::new("secondary-l", FocusPrompt, None),
    KeyBinding::new("secondary-1", Bot1, None),
    KeyBinding::new("secondary-2", Bot2, None),
    KeyBinding::new("secondary-3", Bot3, None),
    KeyBinding::new("secondary-4", Bot4, None),
    KeyBinding::new("secondary-5", Bot5, None),
    KeyBinding::new("secondary-6", Bot6, None),
    KeyBinding::new("secondary-7", Bot7, None),
    KeyBinding::new("secondary-8", Bot8, None),
    KeyBinding::new("secondary-9", Bot9, None),
    KeyBinding::new("alt-up", PrevBot, None),
    KeyBinding::new("alt-down", NextBot, None),
    KeyBinding::new("secondary-[", Back, None),
    KeyBinding::new("secondary-]", Forward, None),
    KeyBinding::new("ctrl-tab", CycleNext, None),
    KeyBinding::new("ctrl-shift-tab", CyclePrev, None),
    KeyBinding::new("secondary-shift-m", Marketplace, None),
    KeyBinding::new("secondary-shift-w", Marketplace, None),
    KeyBinding::new("secondary-shift-,", ToggleBotSettings, None),
    KeyBinding::new("secondary-shift-i", Details, None),
    KeyBinding::new("secondary-alt-b", Details, None),
    KeyBinding::new("ctrl-alt-b", Details, None),
    KeyBinding::new("secondary-enter", SendAnywhere, None),
    KeyBinding::new("secondary-d", Dictate, None),
    KeyBinding::new("secondary-=", ZoomIn, None),
    KeyBinding::new("secondary-+", ZoomIn, None),
    KeyBinding::new("secondary--", ZoomOut, None),
    KeyBinding::new("secondary-0", ZoomReset, None),
    KeyBinding::new("f11", Fullscreen, None),
    KeyBinding::new("ctrl-secondary-f", Fullscreen, None),
    KeyBinding::new("escape", Cancel, Some(CONTEXT)),
    KeyBinding::new("secondary-w", CloseWindow, None),
    KeyBinding::new("secondary-shift-o", OpenComputer, None),
    KeyBinding::new("secondary-shift-b", OpenBrowser, None),
    KeyBinding::new("secondary-shift-t", OpenTerminal, None),
    KeyBinding::new("secondary-.", StopBot, None),
  ]);
}
