//! Translation tables, one file per language (generated by scripts/i18n.py),
//! each a sorted slice of (English, translation) searched by binary search.

mod af;
mod ar;
mod bn;
mod cs;
mod da;
mod de;
mod el;
mod es;
mod fi;
mod fr;
mod he;
mod hi;
mod hu;
mod id;
mod it;
mod ja;
mod ko;
mod nb;
mod nl;
mod pl;
mod pt;
mod ru;
mod sv;
mod th;
mod tr;
mod uk;
mod ur;
mod vi;
mod zhhans;
mod zhhant;

pub fn lookup(code: &str, en: &str) -> Option<&'static str> {
  let table: &[(&str, &str)] = match code {
    "af" => af::TABLE,
    "ar" => ar::TABLE,
    "bn" => bn::TABLE,
    "cs" => cs::TABLE,
    "da" => da::TABLE,
    "de" => de::TABLE,
    "el" => el::TABLE,
    "es" => es::TABLE,
    "fi" => fi::TABLE,
    "fr" => fr::TABLE,
    "he" => he::TABLE,
    "hi" => hi::TABLE,
    "hu" => hu::TABLE,
    "id" => id::TABLE,
    "it" => it::TABLE,
    "ja" => ja::TABLE,
    "ko" => ko::TABLE,
    "nb" => nb::TABLE,
    "nl" => nl::TABLE,
    "pl" => pl::TABLE,
    "pt" => pt::TABLE,
    "ru" => ru::TABLE,
    "sv" => sv::TABLE,
    "th" => th::TABLE,
    "tr" => tr::TABLE,
    "uk" => uk::TABLE,
    "ur" => ur::TABLE,
    "vi" => vi::TABLE,
    "zh-hans" => zhhans::TABLE,
    "zh-hant" => zhhant::TABLE,
    _ => return None,
  };
  table.binary_search_by(|(k, _)| k.as_bytes().cmp(en.as_bytes())).ok().map(|i| table[i].1)
}
