#!/usr/bin/env python3
"""Generate the app's translation tables.

Sources: crates/app/i18n/<code>.json, each an object mapping an English UI
string (as written in the Rust source) to its translation. Output:
crates/app/src/i18n/lang/<code>.rs with a sorted (English, translation)
slice, plus lang/mod.rs dispatching by language code.

Usage: scripts/i18n.py            # regenerate
       scripts/i18n.py --missing  # count strings missing a translation per language
       scripts/i18n.py --extract  # print UI strings in the source not yet in en.json
"""
import json, os, re, sys, glob

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, "crates/app/i18n")
out = os.path.join(root, "crates/app/src/i18n/lang")

def module(code):
    return code.replace("-", "")

# File names carry no hyphens; the runtime codes for Chinese do.
CODES = {"zhhans": "zh-hans", "zhhant": "zh-hant"}

def check(code, table):
    bad = []
    for k, v in table.items():
        if v.count("{}") != k.count("{}"):
            bad.append(f"{code}: placeholder mismatch: {k!r}")
        if re.search(r'(?<!\\)"', v) or "\n" in v or re.search(r'\\(?!")', v):
            bad.append(f"{code}: bad escape: {k!r}")
    return bad

LIT = r'"((?:[^"\\]|\\.)*)"'

def extract():
    """UI strings in the source: t()/tf() literals, plus labels that reach
    t() through tables (sidebar entries, settings pages, tabs, presets,
    catalog entries, teammate suggestions)."""
    found = set()
    for f in glob.glob(os.path.join(root, "crates/app/src/**/*.rs"), recursive=True):
        if "/i18n/lang/" in f:
            continue
        text = open(f).read()
        for m in re.finditer(r"\btf?\(\s*" + LIT, text):
            found.add(m.group(1))
        for m in re.finditer(r'entry\("[\w-]+", IconName::\w+, ' + LIT, text):
            found.add(m.group(1))
        for m in re.finditer(r'\((?:Tab::\w+|"\w+"), ' + LIT + r'(?:, IconName::\w+)?\)', text):
            found.add(m.group(1))
        for m in re.finditer(r"swatches\(" + LIT, text):
            found.add(m.group(1))
        for m in re.finditer(r'label: ' + LIT, text):
            found.add(m.group(1))
    catalog = open(os.path.join(root, "crates/agent/src/catalog.rs")).read()
    for m in re.finditer(r'e\("[\w-]+", "[^"]+", ' + LIT + ", " + LIT + r"\)", catalog):
        found.update([m.group(1), m.group(2)])
    preset = open(os.path.join(root, "crates/provider/src/preset.rs")).read()
    for m in re.finditer(r'\("[\w-]+", ' + LIT + r"\)", preset):
        found.add(m.group(1))
    return {x for x in found if x.strip() and "\n" not in x}

def main():
    if "--extract" in sys.argv:
        english = set(json.load(open(os.path.join(src, "en.json"))))
        for x in sorted(extract() - english):
            print(x)
        return
    codes = sorted(os.path.basename(p)[:-5] for p in glob.glob(os.path.join(src, "*.json")) if not p.endswith("/en.json"))
    english = [e for e in json.load(open(os.path.join(src, "en.json"))) if "\n" not in e and not e.startswith('"')]
    if "--missing" in sys.argv:
        for code in codes:
            t = json.load(open(os.path.join(src, f"{code}.json")))
            miss = [e for e in english if e not in t]
            print(code, len(miss))
        return
    problems = []
    os.makedirs(out, exist_ok=True)
    arms = []
    for code in codes:
        table = json.load(open(os.path.join(src, f"{code}.json")))
        table = {k: v for k, v in table.items() if k in english and v}
        problems += check(code, table)
        rows = sorted(table.items(), key=lambda kv: kv[0].replace("\\\"", "\"").encode("utf-8"))
        mod = module(code)
        with open(os.path.join(out, f"{mod}.rs"), "w") as f:
            f.write(f"//! Generated by scripts/i18n.py from crates/app/i18n/{code}.json.\n\n")
            f.write("pub const TABLE: &[(&str, &str)] = &[\n")
            for k, v in rows:
                f.write(f'  ("{k}", "{v}"),\n')
            f.write("];\n")
        arms.append((CODES.get(code, code), mod))
    with open(os.path.join(out, "mod.rs"), "w") as f:
        f.write("//! Translation tables, one file per language (generated by scripts/i18n.py),\n")
        f.write("//! each a sorted slice of (English, translation) searched by binary search.\n\n")
        for _, mod in arms:
            f.write(f"mod {mod};\n")
        f.write("\npub fn lookup(code: &str, en: &str) -> Option<&'static str> {\n")
        f.write("  let table: &[(&str, &str)] = match code {\n")
        for code, mod in arms:
            f.write(f'    "{code}" => {mod}::TABLE,\n')
        f.write("    _ => return None,\n  };\n")
        f.write("  table.binary_search_by(|(k, _)| k.as_bytes().cmp(en.as_bytes())).ok().map(|i| table[i].1)\n}\n")
    for p in problems:
        print(p)
    print(f"generated {len(arms)} languages")
    sys.exit(1 if problems else 0)

if __name__ == "__main__":
    main()
